### PR TITLE
CPI Latest update

### PR DESCRIPTION
**Pull request by zelima**

### CODE REVIEW

**Comment by rgrp** [comment]
@zelima have you checked the csv diff to check it makes sense (using git diff etc)? Because it is so large i cannot view it here to check that we have sensible changes. Best would be to paste a small sample here.

**Comment by zelima** [comment]
@rgrp Yes I've checked. New file has 188 more rows. 2013 and 2014 year CPI added for countries.
ex. 
First few rows from Previous file:

Country Name,Country Code,Year,CPI
Afghanistan,AFG,2004,89.1695876693231
Afghanistan,AFG,2005,100
Afghanistan,AFG,2006,103.489658996532
Afghanistan,AFG,2007,121.031856608691
Afghanistan,AFG,2008,148.516208531376
Afghanistan,AFG,2009,128.873742241742
Afghanistan,AFG,2010,145.474021679201
Afghanistan,AFG,2011,153.746214799551
Afghanistan,AFG,2012,164.198370349384
Albania,ALB,1991,5.90104378434788

New FIle:

Country Name,Country Code,Year,CPI
Afghanistan,AFG,2004,63.1318927309003
Afghanistan,AFG,2005,71.1409742918197
Afghanistan,AFG,2006,76.3021776776999
Afghanistan,AFG,2007,82.7748069188245
Afghanistan,AFG,2008,108.066600010077
Afghanistan,AFG,2009,99.1153588128686
Afghanistan,AFG,2010,100
Afghanistan,AFG,2011,110.201660141582
Afghanistan,AFG,2012,118.156300027035
**Afghanistan,AFG,2013,127.20035727534
Afghanistan,AFG,2014,133.057086584945**
Albania,ALB,1991,5.11561640084525

**Comment by zelima** [comment]
OK, now I see entire data is different.

I have done no changes to code, it uses the same exact link.

**Comment by rgrp** [comment]
@zelima i wonder if the base index year has changed (i.e. which year is "100"). Does the source indicate what the base year is?

**Comment by zelima** [comment]
@rgrp I guess you are right. Base index now year is 2010.
here is  the link
http://data.worldbank.org/indicator/FP.CPI.TOTL

**Comment by rgrp** [comment]
@zelima do you know what the base year was before? Otherwise this does not explain the change.

**Comment by zelima** [comment]
Before it was 2005 as written in datapackage.json.

**Comment by rgrp** [comment]
@zelima great, thanks.

**Comment by rgrp** [comment]
@zelima see the commit message i did for the commit as an example for you for the future:

https://github.com/datasets/cpi/commit/599fbbf67d5b7ae736c3379212f4038d074fdf08

```
[data]: update with latest data (nb: all data has changed).

* All data has changed because World Bank base year for data changed from 2005 to 2010 since last commit (dec 2013).
```

This is the kind of message you could put in your commit where you added all the data. This would mean my merge would not have needed a comment :-)

**Comment by zelima** [comment]
No problem :)

**Pull request merged**
